Added Product class
PppTours/CafeteriaManager pull request #18
Opened 2021-11-25 15:17 UTC by AdamWizard

closes #7

2021-11-25 15:39 UTC, jumsee requested changes
Some feedback to check

2021-11-25 15:39 UTC, jumsee commented on src/main/java/fr/ppptours/cafetaria/model/Product.java
> +    /**
We could maybe add a constructor that auto generates the tags list. It would facilitate the creation of a product with no initial tags.

2021-11-25 15:39 UTC, jumsee commented on src/main/java/fr/ppptours/cafetaria/model/Product.java
> +    public Iterable<ProductTag> getTags(){
Does iterable not allow for modification? We might be able to modify a product's tags just by getting it. If this is the case and is intended behaviour then it should be mentioned in the documentation of product.

2021-11-25 16:17 UTC, Banalian reviewed
If you're using Lists to store the tags instead of ArrayLists, maybe the Javadoc and code should be changed appropriately ?

2021-11-25 16:17 UTC, Banalian commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    public Product(String name, ArrayList<ProductTag> tags) {
If you're using Lists to store the tags instead of ArrayLists, maybe the Javadoc and code should be changed appropriately ?

2021-11-25 16:17 UTC, Banalian commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    public void addTags(ArrayList<ProductTag> newTags){
Same question/suggestion : replace by list to it's uniform

2021-11-25 16:17 UTC, Banalian commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    public void removeTags(ArrayList<ProductTag> remTags){
Same question/suggestion : replace by list to it's uniform

2021-11-25 19:37 UTC, Nowp requested changes

2021-11-25 19:37 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    public Product(String name, ArrayList<ProductTag> tags) {
Product can initialize the tag list by itself

2021-11-25 19:37 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    public void addTags(ArrayList<ProductTag> newTags){
Maybe we don't need to specify ArrayList and could use List or even Collection or Iterable.
Look what removeAll/addAll need

2021-11-25 19:37 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    public void removeTags(ArrayList<ProductTag> remTags){
https://github.com/PppTours/CafeteriaManager/pull/18/files#r757016573

2021-11-30 15:57 UTC, Nowp requested changes

2021-11-30 15:57 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    }
No need of this parameter "tags", Product can be initialized empty but you can let this constructor as a comfort constructor to init the Product with all its tags but in this cas only an Iterable is needed I think

2021-11-30 15:57 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    }
We could have some documentation here since Tags are not that obvious. 

You can set the return type to Iterable to hide the add/remove from List or just use ImmutableList.
If you can't see which one is better I can explain you on discord or with a nice drink at your place with some candles and... or the cafeteria.

2021-12-02 13:45 UTC, AdamWizard commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    }
thanks for the critic on that, didn't know how to really prevent mofidication out of the getter until i realized Collections litterally has an unmodifiableList class ...

2021-12-02 18:54 UTC, Banalian commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    }
You should specify that it won't add the tag if it is already in the list (either in the Javadoc, or maybe by throwing an exception ? but this seems too extreme)

2021-12-02 18:55 UTC, Banalian approved these changes
The class seems nice, good job !

2021-12-05 12:41 UTC, jumsee approved these changes
Ok from me!

2021-12-05 22:50 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    }
![image](https://user-images.githubusercontent.com/13500119/144767033-3f8ca168-3af6-4972-8d53-8d8f31d4290c.png)

2021-12-05 22:50 UTC, Nowp requested changes

2021-12-05 22:50 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/Product.java
> +    public Product(String name, Collection<ProductTag> tags) {
![image](https://user-images.githubusercontent.com/13500119/144767050-673ad613-6795-4f14-bc8e-b74c98de3a2e.png)

2022-01-16 23:03 UTC, Nowp approved these changes

2022-01-27 13:50 UTC, merged