Added Payment Method class
PppTours/CafeteriaManager pull request #19
Opened 2021-11-25 17:07 UTC by Banalian

closes #3

I took the liberty of creating specific isMethod for the current known methods, but maybe they should be removed since there is the general one ?

2021-11-25 19:42 UTC, Nowp requested changes
Why create a class if our values are only defined by the Method enum ?
Payment method should only have a name at least.

2021-11-25 19:42 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/paymentmethod/Method.java
> +}
Not good, this is not very evolutive

2021-11-25 21:16 UTC, Banalian commented on src/main/java/fr/ppptours/cafeteria/model/paymentmethod/Method.java
> +}
So we'd just have a PaymentMethod class with a name variable, and the check/get function ?

2021-11-26 12:17 UTC, Nowp requested changes

2021-11-26 12:17 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/paymentmethod/Method.java
> +}
Just a class with a name lilianx

2021-11-28 11:02 UTC, jumsee approved these changes
Seems good for me

2021-11-29 20:10 UTC, AdamWizard approved these changes
Looks okay to me.

2021-11-30 15:22 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/paymentmethod/PaymentMethod.java
> +    private String method;
rename to name

2021-11-30 15:38 UTC, Banalian commented on src/main/java/fr/ppptours/cafeteria/model/paymentmethod/PaymentMethod.java
>      }
would id also be a String or a Int ?

2021-12-02 13:49 UTC, AdamWizard approved these changes

2021-12-02 13:56 UTC, Nowp approved these changes

2021-12-02 16:20 UTC, merged

2021-12-05 12:42 UTC, jumsee reviewed
Seems good