Added nextYear variable
PppTours/CafeteriaManager pull request #23
Opened 2021-12-09 13:40 UTC by Banalian

closes #16

2021-12-09 14:28 UTC, jumsee requested changes

2021-12-09 14:28 UTC, jumsee commented on src/main/java/fr/ppptours/cafeteria/model/tags/YearTag.java
> +     * the next year the client will be in
Capitilization please :)

2021-12-17 15:48 UTC, jumsee approved these changes
Good job!

2022-01-07 15:47 UTC, AdamWizard approved these changes

2022-01-07 18:55 UTC, merged