Added ClientAccount
PppTours/CafeteriaManager pull request #25
Opened 2021-12-16 14:26 UTC by Banalian

closes #13

2021-12-17 15:48 UTC, jumsee requested changes
Small changes / suggestions we could add to this MR

2021-12-17 15:48 UTC, jumsee commented on src/main/java/fr/ppptours/cafeteria/model/ClientAccount.java
> +        this.clientBalance = new Balance();
Maybe a constructor with an existing balance to allow for easy deployment (transfer of previous balances)

2021-12-17 15:48 UTC, jumsee commented on src/main/java/fr/ppptours/cafeteria/model/ClientAccount.java
> +        currentYearTag = currentYearTag.getNextYear();
How do we manage the case where the person is in 5th year (or has already graduated)?

2021-12-17 15:53 UTC, Banalian commented on src/main/java/fr/ppptours/cafeteria/model/ClientAccount.java
> +        currentYearTag = currentYearTag.getNextYear();
i tough the last yearTag possible could be "Graduate" and then next would either be null or give itself, but in the getNextYear if the next is null, it would return itself

2021-12-17 15:53 UTC, Banalian commented on src/main/java/fr/ppptours/cafeteria/model/ClientAccount.java
> +        this.clientBalance = new Balance();
will do !

2021-12-22 13:58 UTC, jumsee commented on src/main/java/fr/ppptours/cafeteria/model/ClientAccount.java
> +        currentYearTag = currentYearTag.getNextYear();
🆗

2022-01-07 15:50 UTC, AdamWizard commented
Does it make sense to instantiate a ClientAccount without any PersonTags? if so, maybe add a constructor that takes no tags?
Other than that comment, looks pretty clear to me.

2022-01-07 15:51 UTC, AdamWizard approved these changes

2022-01-07 18:55 UTC, Banalian commented
@AdamWizard Well you could always give a null list. But i think everyone would have at least one tag, saying he's a student or a teacher maybe, or a Kfetier.

2022-01-16 23:04 UTC, Nowp approved these changes

2022-01-16 23:04 UTC, Nowp commented on src/main/java/fr/ppptours/cafeteria/model/ClientAccount.java
> +import java.util. ArrayList;
```suggestion
import java.util.ArrayList;
```

2022-01-17 20:56 UTC, jumsee approved these changes

2022-01-18 21:04 UTC, merged